plugins {
    id 'java-library'
}

repositories {
    maven {
        url repoUrl
        allowInsecureProtocol = true
    }
    mavenCentral()
}


configurations.configureEach {
    exclude group: "io.netty", module: "netty-transport-native-io_uring"
    exclude group: "io.netty", module: "netty-transport-classes-io_uring"
    resolutionStrategy {
        force(libs.hikaricp)
    }
}

dependencies {
}

java {
    withSourcesJar()
}

tasks.test {
    useJUnitPlatform()
}
