micronaut:
  application:
    name: flow
  config-client:
    enabled: true
  metrics:
    enabled: true
    binders:
      jvm: true
      logback: true
      uptime: true
    export:
      prometheus:
        enabled: true
        step: 5s   # 指标采集间隔
  server:
    thread-selection: AUTO
    idle-timeout: 3m
    port: 3434
#    port: 3340
    notFoundOnMissingBody: false
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins-regex: ".*"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
  router:
    versioning:
      enabled: true
      default-version: v1
      parameter:
        enabled: true   # 👈 如果你想用 ?api-version=v1 这种形式
        names: 'v,api-version'
      header:
        enabled: true   # 👈 如果你想用请求头 X-API-VERSION: v1 这种形式
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'

cluster:
  dataCenter: "beijing"
  clusterName: "okr"
jackson:
  serializationInclusion: NON_NULL
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true

endpoints:
  health:
    elasticsearch:
      enabled: false
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false


path:
  configPath: "/workspace/java/cses/server/conf/"

