micronaut:
  router:
    static-resources:
      flow-studio:
        mapping: /demo/**
        paths:
          - classpath:flow-demo

flow:
  studio:
    enabled: true
    session-binder:
      enabled: true
    company-id: ${FLOW_STUDIO_COMPANY_ID:flow-demo}
    user-id: ${FLOW_STUDIO_USER_ID:studio-user}
    user-name: ${FLOW_STUDIO_USER_NAME:Flow Studio User}
