plugins {
    id 'org.flow.build.base'
    alias(libs.plugins.micronaut.application)
    alias(libs.plugins.shadow)
    alias(libs.plugins.micronaut.aot)
    id 'java-library'
}

// 将代码中的 repositories 替换为如下所示
repositories {
    maven {
        url = uri(repoUrl)
        allowInsecureProtocol = true
    }
    mavenCentral()
    gradlePluginPortal()
}

configurations.configureEach {
    exclude group: "io.netty", module: "netty-transport-native-io_uring"
    exclude group: "io.netty", module: "netty-transport-classes-io_uring"
    exclude group: "org.paas", module: "paas-diagnostic"
    exclude group: "org.paas", module: "paas-response-wrapper"
    exclude group: "org.paas", module: "paas-temporal"
    resolutionStrategy {
        force(libs.hikaricp)
    }
}

dependencies {
    api(project(':core'))

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
    annotationProcessor(libs.micronaut.http.validation)

    implementation(libs.micronaut.http.client)
    implementation(libs.micronaut.discovery.client)
    implementation(libs.micronaut.elasticsearch)
    implementation(libs.micronaut.jackson.databind)
    implementation(libs.jackson.dataformat.yaml)
    api(libs.opentelemetry.exporter.otlp)

    runtimeOnly(libs.logback.classic)

    testImplementation(libs.micronaut.validation)
    testImplementation(libs.logback.classic)
    testRuntimeOnly(libs.junit.platform.launcher)
    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)
    testAnnotationProcessor(libs.micronaut.http.validation)
}

application {
    mainClass = "org.cses.flow.Application"
}

graalvmNative.toolchainDetection = false

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("org.cses.flow.*")
    }
    aot {
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}

tasks.named("dockerfileNative") {
    jdkVersion = "21"
}

tasks.configureEach {
    if (name in ["shadowJar", "optimizedJitJarAll"]) {
        zip64 = true
        mergeServiceFiles()
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}
