micronaut:
  application:
    name: cses
    instance:
      id: cses
  config-client:
    enabled: false
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
  server:
    idle-timeout: -1m
    port: 8080
environment:
  production: true
  localIp: "196.168.1.99"
  dataCenter: "beijing"
  cluster: "okr"
jackson:
  serializationInclusion: NON_NULL
consul:
  client:
    registration:
      enabled: false
    defaultZone: "http://192.168.6.6:8500" # prod
#    defaultZone: "http://consul-pre.jinqidongli.com/" # pre
#    defaultZone: [ "http://193.168.2.100:32267" ]  # dev
#    defaultZone: [ "http://consul-test-2-0.consul-test-2.consul.svc.cluster.local:8500" ] # dev (打包使用)
    config:
      path: "X9-Config/"
#      path: "X9-Config-Migrate"
      format: "YAML"
      datacenter: "beijing"
      separator: "/"
      raw: true
    watch:
      enabled: false

grpc:
  server:
    instance-id: 'cses-grpc-im'
    enabled: false
    port: 3388
  client:
    plaintext: true
    discovery:
      enabled: false
    max-retry-attempts: 10

path:
  configPath: "/workspace/java/cses/server/conf/"

thrift:
  server:
    instance-id: 'cses-thrift'
    enabled: true
#neo4j:
#  uri: "bolt://192.168.6.233:7687"
#  hosts: ["192.168.6.233:7687"]
#  username: "neo4j"
#  password: "neo4j"
#  database: "neo4j"  # 可选，指定默认数据库
#  config:
#    connection-timeout: 5000  # 可选，连接超时配置

otel:
  instrumentation:
    jdbc:
      enabled: false


